<!DOCTYPE HTML>
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<title>Currency converter PHP Script</title>
</head>
<body>
<div border:1px solid blue>
	<form action="" method="POST">
		<p>Value:<input type="text" name="currency" value=""/>&nbsp;&nbsp;From:
		<select name="fromcurrency">
			<option value="AED">United Arab Emirates</option>
			<option value="AFN">Afghanistan</option>
			<option value="ALL">Albania</option>
			<option value="AMD">Armenia</option>
			<option value="ANG">Netherlands Antilles</option>
			<option value="AOA">Angola</option>
			<option value="ARS">Argentina</option>
			<option value="AUD">Australia,</option>
			<option value="AWG">Aruba</option>
			<option value="AZN">Azerbaijan</option>
			<option value="BAM">Bosnia and Herzegovina</option>
			<option value="BBD">Barbados</option>
			<option value="BDT">Bangladesh</option>
			<option value="BGN">Bulgaria</option>
			<option value="BHD">Bahrain</option>
			<option value="BIF">Burundi</option>
			<option value="BMD">Bermuda</option>
			<option value="BND">Brunei</option>
			<option value="BOB">Bolivia</option>
			<option value="BRL">Brazil</option>
			<option value="BSD">Bahamas</option>
			<option value="BTN">Bhutan</option>
			<option value="BWP">Botswana</option>
			<option value="BYR">Belarus</option>
			<option value="BZD">Belize</option>
			<option value="CAD">Canada</option>
			<option value="CDF">Democratic Republic of Congo</option>
			<option value="CHE">Switzerland</option>
			<option value="CHF">Switzerland, Liechtenstein</option>
			<option value="CHW">Switzerland</option>
			<option value="CLF">Chile</option>
			<option value="CNY">Mainland China</option>
			<option value="COP">Colombia</option>
			<option value="CRC">Costa Rica</option>
			<option value="CUP">Cuba</option>
			<option value="CVE">Cape Verde</option>
			<option value="CYP">Cyprus</option>
			<option value="CZK">Czech Republic</option>
			<option value="DJF">Djibouti</option>
			<option value="DKK">Denmark, Faroe Islands, Greenland</option>
			<option value="DOP">Dominican Republic</option>
			<option value="DZD">Algeria</option>
			<option value="EEK">Estonia</option>
			<option value="EGP">Egypt</option>
			<option value="ERN">Eritrea</option>
			<option value="ETB">Ethiopia</option>
			<option value="EUR">European Union, see eurozone</option>
			<option value="FJD">Fiji</option>
			<option value="FKP">Falkland Islands</option>
			<option value="GBP">United Kingdom</option>
			<option value="GEL">Georgia</option>
			<option value="GHS">Ghana</option>
			<option value="GIP">Gibraltar</option>
			<option value="GMD">Gambia</option>
			<option value="GNF">Guinea</option>
			<option value="GTQ">Guatemala</option>
			<option value="GYD">Guyana</option>
			<option value="HKD">Hong Kong Special Administrative Region</option>
			<option value="HNL">Honduras</option>
			<option value="HRK">Croatia</option>
			<option value="HTG">Haiti</option>
			<option value="HUF">Hungary</option>
			<option value="IDR">Indonesia</option>
			<option value="ILS">Israel</option>
			<option value="INR">Bhutan, India</option>
			<option value="IQD">Iraq</option>
			<option value="IRR">Iran</option>
			<option value="ISK">Iceland</option>
			<option value="JMD">Jamaica</option>
			<option value="JOD">Jordan</option>
			<option value="JPY">Japan</option>
			<option value="KES">Kenya</option>
			<option value="KGS">Kyrgyzstan</option>
			<option value="KHR">Cambodia</option>
			<option value="KMF">Comoros</option>
			<option value="KPW">North Korea</option>
			<option value="KRW">South Korea</option>
			<option value="KWD">Kuwait</option>
			<option value="KYD">Cayman Islands</option>
			<option value="KZT">Kazakhstan</option>
			<option value="LAK">Laos</option>
			<option value="LBP">Lebanon</option>
			<option value="LSL">Lesotho</option>
			<option value="LTL">Lithuania</option>
			<option value="LVL">Latvia</option>
			<option value="LVL">Latvia</option>
			<option value="LYD">Libya</option>
			<option value="MAD">Morocco, Western Sahara</option>
			<option value="MDL">Moldova</option>
			<option value="MGA">Madagascar</option>
			<option value="MKD">Former Yugoslav Republic of Macedonia</option>
			<option value="MMK">Myanmar</option>
			<option value="MNT">Mongolia</option>
			<option value="MOP">Macau Special Administrative Region</option>
			<option value="MRO">Mauritania</option>
			<option value="MTL">Malta</option>
			<option value="MUR">Mauritius</option>
			<option value="MVR">Maldives</option>
			<option value="MWK">Malawi</option>
			<option value="MXN">Mexico</option>
			<option value="MYR">Malaysia</option>
			<option value="MZN">Mozambique</option>
			<option value="NAD">Namibia</option>
			<option value="NGN">Nigeria</option>
			<option value="NIO">Nicaragua</option>
			<option value="NOK">Norway</option>
			<option value="NPR">Nepal</option>
			<option value="NZD">Cook Islands, New Zealand, Niue, Pitcairn, Tokelau</option>
			<option value="OMR">Oman</option>
			<option value="PAB">Panama</option>
			<option value="PEN">Peru</option>
			<option value="PGK">Papua New Guinea</option>
			<option value="PHP">Philippines</option>
			<option value="PKR">Pakistan</option>
			<option value="PLN">Poland</option>
			<option value="PYG">Paraguay</option>
			<option value="QAR">Qatar</option>
			<option value="RON">Romania</option>
			<option value="RSD">Serbia</option>
			<option value="RUB">Russia, Abkhazia, South Ossetia</option>
			<option value="RWF">Rwanda</option>
			<option value="SAR">Saudi Arabia</option>
			<option value="SBD">Solomon Islands</option>
			<option value="SCR">Seychelles</option>
			<option value="SDG">Sudan</option>
			<option value="SEK">Sweden</option>
			<option value="SGD">Singapore</option>
			<option value="SHP">Saint Helena</option>
			<option value="SKK">Slovakia</option>
			<option value="SLL">Sierra Leone</option>
			<option value="SRD">Suriname</option>
			<option value="STD">São Tomé and Príncipe</option>
			<option value="SYP">Syria</option>
			<option value="SZL">Swaziland</option>
			<option value="THB">Thailand</option>
			<option value="TJS">Tajikistan</option>
			<option value="TMM">Turkmenistan</option>
			<option value="TND">Tunisia</option>
			<option value="TOP">Tonga</option>
			<option value="TRY">Turkey</option>
			<option value="TTD">Trinidad and Tobago</option>
			<option value="TWD">Taiwan</option>
			<option value="TZS">Tanzania</option>
			<option value="UAH">Ukraine</option>
			<option value="UGX">Uganda</option>
			<option value="USD">United States</option>
			<option value="USD">Ecuador</option>
			<option value="USD">Haiti</option>
			<option value="UYU">Uruguay</option>
			<option value="UZS">Uzbekistan</option>
			<option value="VEB">Venezuela</option>
			<option value="VND">Vietnam</option>
			<option value="VUV">Vanuatu</option>
			<option value="WST">Samoa</option>
			<option value="XAF">Cameroon, Central African Republic, Congo, Chad, Equatorial Guinea, Gabon</option>
			<option value="XOF">Benin, Burkina Faso, Côte d'Ivoire, Guinea-Bissau, Mali, Niger, Senegal, Togo</option>
			<option value="XPF">French Polynesia, New Caledonia, Wallis and Futuna</option>
			<option value="YER">Yemen</option>
			<option value="ZAR">South Africa</option>
			<option value="ZMK">Zambia</option>
			<option value="ZWD">Zimbabwe</option>
		</select> &nbsp;&nbsp;To:
		<select name="tocurrency">
			<option value="AED">United Arab Emirates</option>
			<option value="AFN">Afghanistan</option>
			<option value="ALL">Albania</option>
			<option value="AMD">Armenia</option>
			<option value="ANG">Netherlands Antilles</option>
			<option value="AOA">Angola</option>
			<option value="ARS">Argentina</option>
			<option value="AUD">Australia,</option>
			<option value="AWG">Aruba</option>
			<option value="AZN">Azerbaijan</option>
			<option value="BAM">Bosnia and Herzegovina</option>
			<option value="BBD">Barbados</option>
			<option value="BDT">Bangladesh</option>
			<option value="BGN">Bulgaria</option>
			<option value="BHD">Bahrain</option>
			<option value="BIF">Burundi</option>
			<option value="BMD">Bermuda</option>
			<option value="BND">Brunei</option>
			<option value="BOB">Bolivia</option>
			<option value="BRL">Brazil</option>
			<option value="BSD">Bahamas</option>
			<option value="BTN">Bhutan</option>
			<option value="BWP">Botswana</option>
			<option value="BYR">Belarus</option>
			<option value="BZD">Belize</option>
			<option value="CAD">Canada</option>
			<option value="CDF">Democratic Republic of Congo</option>
			<option value="CHE">Switzerland</option>
			<option value="CHF">Switzerland, Liechtenstein</option>
			<option value="CHW">Switzerland</option>
			<option value="CLF">Chile</option>
			<option value="CNY">Mainland China</option>
			<option value="COP">Colombia</option>
			<option value="CRC">Costa Rica</option>
			<option value="CUP">Cuba</option>
			<option value="CVE">Cape Verde</option>
			<option value="CYP">Cyprus</option>
			<option value="CZK">Czech Republic</option>
			<option value="DJF">Djibouti</option>
			<option value="DKK">Denmark, Faroe Islands, Greenland</option>
			<option value="DOP">Dominican Republic</option>
			<option value="DZD">Algeria</option>
			<option value="EEK">Estonia</option>
			<option value="EGP">Egypt</option>
			<option value="ERN">Eritrea</option>
			<option value="ETB">Ethiopia</option>
			<option value="EUR">European Union, see eurozone</option>
			<option value="FJD">Fiji</option>
			<option value="FKP">Falkland Islands</option>
			<option value="GBP">United Kingdom</option>
			<option value="GEL">Georgia</option>
			<option value="GHS">Ghana</option>
			<option value="GIP">Gibraltar</option>
			<option value="GMD">Gambia</option>
			<option value="GNF">Guinea</option>
			<option value="GTQ">Guatemala</option>
			<option value="GYD">Guyana</option>
			<option value="HKD">Hong Kong Special Administrative Region</option>
			<option value="HNL">Honduras</option>
			<option value="HRK">Croatia</option>
			<option value="HTG">Haiti</option>
			<option value="HUF">Hungary</option>
			<option value="IDR">Indonesia</option>
			<option value="ILS">Israel</option>
			<option value="INR">Bhutan, India</option>
			<option value="IQD">Iraq</option>
			<option value="IRR">Iran</option>
			<option value="ISK">Iceland</option>
			<option value="JMD">Jamaica</option>
			<option value="JOD">Jordan</option>
			<option value="JPY">Japan</option>
			<option value="KES">Kenya</option>
			<option value="KGS">Kyrgyzstan</option>
			<option value="KHR">Cambodia</option>
			<option value="KMF">Comoros</option>
			<option value="KPW">North Korea</option>
			<option value="KRW">South Korea</option>
			<option value="KWD">Kuwait</option>
			<option value="KYD">Cayman Islands</option>
			<option value="KZT">Kazakhstan</option>
			<option value="LAK">Laos</option>
			<option value="LBP">Lebanon</option>
			<option value="LSL">Lesotho</option>
			<option value="LTL">Lithuania</option>
			<option value="LVL">Latvia</option>
			<option value="LVL">Latvia</option>
			<option value="LYD">Libya</option>
			<option value="MAD">Morocco, Western Sahara</option>
			<option value="MDL">Moldova</option>
			<option value="MGA">Madagascar</option>
			<option value="MKD">Former Yugoslav Republic of Macedonia</option>
			<option value="MMK">Myanmar</option>
			<option value="MNT">Mongolia</option>
			<option value="MOP">Macau Special Administrative Region</option>
			<option value="MRO">Mauritania</option>
			<option value="MTL">Malta</option>
			<option value="MUR">Mauritius</option>
			<option value="MVR">Maldives</option>
			<option value="MWK">Malawi</option>
			<option value="MXN">Mexico</option>
			<option value="MYR">Malaysia</option>
			<option value="MZN">Mozambique</option>
			<option value="NAD">Namibia</option>
			<option value="NGN">Nigeria</option>
			<option value="NIO">Nicaragua</option>
			<option value="NOK">Norway</option>
			<option value="NPR">Nepal</option>
			<option value="NZD">Cook Islands, New Zealand, Niue, Pitcairn, Tokelau</option>
			<option value="OMR">Oman</option>
			<option value="PAB">Panama</option>
			<option value="PEN">Peru</option>
			<option value="PGK">Papua New Guinea</option>
			<option value="PHP">Philippines</option>
			<option value="PKR">Pakistan</option>
			<option value="PLN">Poland</option>
			<option value="PYG">Paraguay</option>
			<option value="QAR">Qatar</option>
			<option value="RON">Romania</option>
			<option value="RSD">Serbia</option>
			<option value="RUB">Russia, Abkhazia, South Ossetia</option>
			<option value="RWF">Rwanda</option>
			<option value="SAR">Saudi Arabia</option>
			<option value="SBD">Solomon Islands</option>
			<option value="SCR">Seychelles</option>
			<option value="SDG">Sudan</option>
			<option value="SEK">Sweden</option>
			<option value="SGD">Singapore</option>
			<option value="SHP">Saint Helena</option>
			<option value="SKK">Slovakia</option>
			<option value="SLL">Sierra Leone</option>
			<option value="SRD">Suriname</option>
			<option value="STD">São Tomé and Príncipe</option>
			<option value="SYP">Syria</option>
			<option value="SZL">Swaziland</option>
			<option value="THB">Thailand</option>
			<option value="TJS">Tajikistan</option>
			<option value="TMM">Turkmenistan</option>
			<option value="TND">Tunisia</option>
			<option value="TOP">Tonga</option>
			<option value="TRY">Turkey</option>
			<option value="TTD">Trinidad and Tobago</option>
			<option value="TWD">Taiwan</option>
			<option value="TZS">Tanzania</option>
			<option value="UAH">Ukraine</option>
			<option value="UGX">Uganda</option>
			<option value="USD">United States</option>
			<option value="USD">Ecuador</option>
			<option value="USD">Haiti</option>
			<option value="UYU">Uruguay</option>
			<option value="UZS">Uzbekistan</option>
			<option value="VEB">Venezuela</option>
			<option value="VND">Vietnam</option>
			<option value="VUV">Vanuatu</option>
			<option value="WST">Samoa</option>
			<option value="XAF">Cameroon, Central African Republic, Congo, Chad, Equatorial Guinea, Gabon</option>
			<option value="XOF">Benin, Burkina Faso, Côte d'Ivoire, Guinea-Bissau, Mali, Niger, Senegal, Togo</option>
			<option value="XPF">French Polynesia, New Caledonia, Wallis and Futuna</option>
			<option value="YER">Yemen</option>
			<option value="ZAR">South Africa</option>
			<option value="ZMK">Zambia</option>
			<option value="ZWD">Zimbabwe</option>
		</select> &nbsp;&nbsp;<input type="submit" name="submit" value="Calculate"/>
		
		</p>
	</form>
	<?php
		if(isset($_POST['submit']) && isset($_POST['currency']))
		{
			if(ctype_digit($_POST['currency']))
			{
				$fromcurrency = $_POST['fromcurrency'];
				$tocurrency = $_POST['tocurrency'];
				$curl = curl_init();
				curl_setopt($curl, CURLOPT_URL, "http://download.finance.yahoo.com/d/quotes.csv?s=$fromcurrency$tocurrency=X&f=sl1&e=.csv");
				curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);			
				$content = curl_exec($curl);			
				curl_close($curl); 
				$value = substr(trim($content), 11, 6);
				$total = $value*trim($_POST['currency']);
				echo "Your Currency value = $total";
			}else{
				echo 'Please put numeric value in value input field.';
			}			
		}		
	?>
	</div>
</body>
</html>




